//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using UnityEngine;
using System.Collections;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class root {
	
	private rootPlace[] itemsField;
	
	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("place", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public rootPlace[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootPlace {
	
	private string placeNameField;
	
	private string placeDescField;
	
	private string xcordinateField;
	
	private string ycordinateField;
	
	private string zcordinateField;
	
	private rootPlaceDepartmentListDepartment[] departmentListField;
	
	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string placeName {
		get {
			return this.placeNameField;
		}
		set {
			this.placeNameField = value;
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string placeDesc {
		get {
			return this.placeDescField;
		}
		set {
			this.placeDescField = value;
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string xcordinate {
		get {
			return this.xcordinateField;
		}
		set {
			this.xcordinateField = value;
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string ycordinate {
		get {
			return this.ycordinateField;
		}
		set {
			this.ycordinateField = value;
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string zcordinate {
		get {
			return this.zcordinateField;
		}
		set {
			this.zcordinateField = value;
		}
	}
	
	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	[System.Xml.Serialization.XmlArrayItemAttribute("department", typeof(rootPlaceDepartmentListDepartment), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public rootPlaceDepartmentListDepartment[] departmentList {
		get {
			return this.departmentListField;
		}
		set {
			this.departmentListField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rootPlaceDepartmentListDepartment {
	
	private string valueField;
	
	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value {
		get {
			return this.valueField;
		}
		set {
			Debug.Log("value===>"+value);
			this.valueField = value;
		}
	}
}
