// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Xml.Serialization;
using UnityEngine;
using System.IO;
using System.Resources;

	public class XMLReader
	{
	public TextAsset GameAsset;
	private root xmlDataStruture;

	public XMLReader (TextAsset gA)
	{
		this.GameAsset = gA;
				
			MemoryStream ms = new MemoryStream(GameAsset.bytes);
				


				XmlSerializer serializer = new XmlSerializer(typeof(root), new XmlRootAttribute("root"));
						
				xmlDataStruture = (root)serializer.Deserialize(ms);

				

				Debug.Log("Number of builds in xml = "+xmlDataStruture.Items.Length);

			}

			public rootPlace[] getList(){
				return xmlDataStruture.Items;	
			}
			
			
	}


